backend:
  name: github
  repo: KCcodes1/samara-repo
  branch: main
  base_url: https://samarahomes.co.ke
  auth_endpoint: /api/decap/auth

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { name: title, widget: string }
          - { name: slug, widget: string, default: "home" }
          - { name: heroTitle, widget: string, required: false }
          - { name: heroSubtitle, widget: string, required: false }
          - { name: heroImage, widget: image, required: false }
          - { name: description, widget: text, required: false }
          - { name: body, widget: markdown, required: false }
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { name: title, widget: string }
          - { name: slug, widget: string, default: "about" }
          - { name: heroTitle, widget: string, required: false }
          - { name: heroSubtitle, widget: string, required: false }
          - { name: heroImage, widget: image, required: false }
          - { name: description, widget: text, required: false }
          - { name: body, widget: markdown, required: false }
      - label: "Services"
        name: "services"
        file: "content/pages/services.md"
        fields:
          - { name: title, widget: string }
          - { name: slug, widget: string, default: "services" }
          - { name: heroTitle, widget: string, required: false }
          - { name: heroSubtitle, widget: string, required: false }
          - { name: heroImage, widget: image, required: false }
          - { name: description, widget: text, required: false }
          - { name: body, widget: markdown, required: false }

  - name: "categories"
    label: "Categories"
    files:
      - label: "Categories List"
        name: "categories_list"
        file: "content/categories/categories.json"
        fields:
          - label: "Categories"
            name: "categories"
            widget: list
            fields:
              - { name: "title", widget: string }
              - { name: "slug", widget: string }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Contact Information"
        name: "contact_info"
        file: "content/settings/contact.json"
        fields:
          - { name: "companyName", widget: string, label: "Company Name" }
          - { name: "address", widget: string, label: "Address" }
          - { name: "phone", widget: string, label: "Phone Number" }
          - { name: "email", widget: string, label: "Email Address" }
          - { name: "whatsappNumber", widget: string, label: "WhatsApp Number" }
          - { name: "whatsappMessage", widget: text, label: "Default WhatsApp Message" }
          - label: "Social Media"
            name: "socials"
            widget: object
            fields:
              - { name: "instagram", widget: string, label: "Instagram URL", required: false }
              - { name: "pinterest", widget: string, label: "Pinterest URL", required: false }
              - { name: "tiktok", widget: string, label: "TikTok URL", required: false }
              - { name: "facebook", widget: string, label: "Facebook URL", required: false }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    summary: "{{title}} | KES {{price}}"
    fields:
      - { name: title, widget: string }
      - { name: slug, widget: string }
      - { name: price, widget: number, value_type: float, required: false }
      - { name: sku, widget: string, required: false }
      - label: Categories
        name: categories
        widget: list
        default: []
        field:
          name: category
          widget: select
          options:
            - { label: "Curtains", value: "curtains" }
            - { label: "Furniture", value: "furniture" }
            - { label: "Lighting", value: "lighting" }
            - { label: "Decor", value: "decor" }
            - { label: "Accessories", value: "accessories" }
      - label: Tags
        name: tags
        widget: list
        default: []
        field: { name: tag, widget: string }
      - label: Dimensions
        name: dimensions
        widget: object
        required: false
        fields:
          - { name: width, widget: number, value_type: float, required: false }
          - { name: height, widget: number, value_type: float, required: false }
          - { name: depth, widget: number, value_type: float, required: false }
      - label: Materials
        name: materials
        widget: list
        default: []
        field: { name: material, widget: string }
      - label: Images
        name: images
        widget: list
        default: []
        field: { name: image, widget: image }
      - { name: featured, widget: boolean, default: false }
      - { name: description, widget: text, required: false }
      - { name: date, widget: datetime, time_format: false, required: false }
      - { name: body, widget: markdown, required: false }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    extension: "md"
    summary: "{{title}} — {{location}}"
    fields:
      - { name: title, widget: string }
      - { name: slug, widget: string }
      - { name: cover, widget: image, required: false }
      - label: Gallery
        name: gallery
        widget: list
        default: []
        field: { name: image, widget: image }
      - { name: location, widget: string, required: false }
      - { name: style, widget: string, required: false }
      - { name: date, widget: datetime, time_format: false, required: false }
      - { name: body, widget: markdown, required: false }